version: "3"
services:
  db:             # DBサーバ用コンテナ
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql-files
      - ./docker/mysql/mysql_init:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf/:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
    - "3306:3306"
  app:            # アプリケーションサーバ用コンテナ
    build:
      context:    ./docker/php
      args:
        - TZ=${TZ}
    volumes:
      - ./src:/work
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir:  /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DOMAINS: 'localhost -> http://web:8000'
      STAGE: 'local'
    volumes:
      - ./docker/nginx/ssl:/var/lib/https-portal
  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=${TZ}
  node:
    image: node:12.8-alpine
    volumes:
      - ./src:/work
    working_dir: /work

volumes:
  db-store:
